#!/bin/csh -f
# @(#) usage: mktex [-x] `ls .` adds .tex; -x removes .tex
#
set option="-n"

top:
while ($#argv > 0)
	switch ("$argv[1]")
		case -*:
			set option="$argv[1]"
			shift argv
		case *:
			set file=$argv[1]
			if ( "$option" == "-x" ) then
				mv $file.tex $file
			else
				mv $file $file.tex
			endif
	endsw
	shift
	goto top
end

