#!/bin/bash
#  provide the info to remote-host from this script
#
function _ssh() {
USER=$1
HOST=$2
PSWD=$3

/usr/local/bin/expect<<EOD
   exp_internal 1
   set timeout 30
   log_user 1
   set send_slow {1 .01}
   log_file ~/log/ssh_tmp.log
   set prompt  {*~\]\$ $}

   send_log "Connecting to $HOST using $USER user\n"
   eval spawn ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 "$USER\@$HOST"
   expect {
      timeout {send_user "timeout while connecting to $HOST\n"; exit }
      "*No route to host*" { send_user "$HOST not reachable\n"; exit }
      "*assword: " { send -s $PSWD\r }
      }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "*Welcome*" {  send_user "Welcome: \n" }
   }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "" {  send_user "... \n" }
   }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "" {  send_user "... \n" }
   }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "" {  send_user "... \n" }
   }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "" {  send_user "... \n" }
   }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "*\]\$ " { send_user "Login successful to $HOST\n" }
   }
   expect {
   while true {
	  timeout { send_user "timeout waiting for input\n"; exit }
	  "" { send_user " ... " ; exit; sleep 10 }
      }
   }
   close
EOD
}
_ssh woo login.cirrus.ac.uk 'CkqY5b5LV<,+UR3T'

