#!/bin/bash
#
#  provide the password to cirrus from this script
#
function _ssh() {
USER=$1
HOST=$2
PSWD=$3

/usr/local/bin/expect<<EOD
   set timeout 30
   log_user 1
   set send_slow {1 .01}
   log_file ~/log/ssh_tmp.log

   send_log "Connecting to $HOST using $USER user\n"
   eval spawn ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=30 "$USER\@$HOST"
   expect {
      timeout {send_user "timeout while connecting to $HOST\n"; exit }
      "*No route to host*" { send_user "$HOST not reachable\n"; exit }
      "*assword: " { send -s $PSWD\r }
      }
   expect {
      timeout { send_user "timeout waiting for prompt\n"; exit }
      "*]#"  { send_user "Login successful to $HOST\n" }
      }
   send "\hostname\r"
   expect {
      "*j#"  { send "exit\r" }
      }
   send_user "Disconnected\n"
   close
EOD
}

_ssh woo login.cirrus.ac.uk 'CkqY5b5LV<,+UR3T'

