#!/bin/bash
#
# Backup a list of database files to ~/backups/sql
#
# Usage: backup_db password
#
FILE=/usr/local/mysql/bin/mysqldump
if [ -e "$FILE" ]; then
while read p; do
/usr/local/mysql/bin/mysqldump $p -u woo -p$1 2>>/Users/woo/logs/cronjob.log 1> /Users/woo/backups/sql/$p.sql
echo "$p backed up"
done <~/backups/files.txt
echo "sql backed up to ~/backups/sql"
echo "cronjob.log at ~/logs/cronjob.log"
fi
echo "All Done!"
