#!/usr/bin/perl -w
#use Term::ANSIColor qw(:constants);
#
# Look at time log and see if anyone is being billed.
#
$file =  "/Users/woo/Dropbox/Personal/Documents/Notes/time_track.txt";
my $lastline = do {
    open my $pipe, '-|', tail => -1, $file
        or die "Can't spawn tail: $!\n";
    <$pipe>;
};
#print $lastline;
$lastline =~ /^\((.*)\s-\s(.*)\)\s(.*)\s@(.*)$/;
   print "$4: $3 since $1\n" unless $2;
   print "No one\n" if $2;
#   print RED,"$4: $3 since $1",RESET unless $2;
#   print GREEN,"No one",RESET if $2;

#print "\nAll Done!\n";
