#!/bin/bash
#
# Look at time log and see if anyone is being billed.
#
billing=`tail -n 1 ~/Dropbox/Personal/Documents/Notes/time_track.txt`
IFS=')' # space is set as delimiter
read -ra ADDR <<< "$billing" # str is read into an array as tokens separated
echo ${ADDR[0]} # This is the time portion, 1 is the task
IFS='-' 
read -ra TIME <<< ${ADDR[0]}
FROM=${TIME[0]}
TO=${TIME[1]}
echo "To: '$TO'"
if [ -z "$TO" ]; then
echo "Working on: ${ADDR[1]} since $FROM"
else
echo "Not billing"
fi
echo "All Done!"
