#!/bin/bash
#
# Checks the git status of the list of git repositories
#
# TODO - 20200321 - woo - The tool says the remote and local are out of
#                         sync when git status says they are okay.
#
index=0
gitrepos=()

declare -a gitrepos=(~/.vim ~/bin /Library/WebServer/Documents/patti /Library/WebServer/Documents/indecks)


for d in "${gitrepos[@]}"; do
    if [ -d $d ]; then
        cd $d
    else
        continue
    fi
    if [  -e $d/.git ]; then

    reponame="`basename $d`"

    ok=true
    git fetch --quiet origin 2>/dev/null
    if [ ! -z "`git diff  2> /dev/null`" ]; then
        echo " $reponame --> Out of sync with origin/HEAD"
        ok=false
    fi
    if [ ! -z "`git ls-files --other --exclude-standard 2> /dev/null`" ]; then
        echo " $reponame --> Untracked files present"
        ok=false
    fi
    if [ ! -z "`git diff --cached --shortstat 2> /dev/null`" ]; then
        echo " $reponame --> Changes to be committed"
        ok=false
    fi
    if [ ! -z "`git diff --shortstat 2> /dev/null`" ]; then
        echo " $reponame --> Changes to be staged/committed"
        ok=false
    fi
    if $ok; then
        echo " OK --> $reponame"
    fi
 fi
done
 echo "All Done!";

