#!/bin/bash
#
# Definition: sync ~/Movies to barsoom/Volumes/iTunes/Movies
#
#
#   This is only run on barsoom, so check for that.
#
LIVE=jwooten37830.com
host=$(hostname)
if [ $host != $LIVE ]
then
    echo "This command is only runnable on $LIVE"
    echo "This hostname is: $host"
    exit
fi
rsync -vaz ~/Movies --rsh="ssh -l woo" barsoom:/Volumes/iTunes
echo "Movies on barsoom synched from ~woo/Movies"
#
# Now sync the iTunes on ~/iTunes to barsoom
#
rsync -vaz ~/iTunes --rsh="ssh -l woo" barsoom:/Volumes/iTunes
echo "iTunes on barsoom synched from ~woo/iTunes"
echo "All Done!"
