#!/bin/bash
#
# Definition: sync ~/Movies to barsoom/Volumes/iTunes/Movies
#
rsync -vaz ~/Movies --rsh="ssh -l woo" barsoom:/Volumes/iTunes
echo "Movies on barsoom synched from ~woo/Movies"
#
# Now sync the iTunes on ~/iTunes to barsoom
#
rsync -vaz ~/iTunes --rsh="ssh -l woo" barsoom:/Volumes/iTunes
echo "iTunes on barsoom synched from ~woo/iTunes"
echo "All Done!"
