#!/bin/bash
#
# Definition: sync Seagate/Movies to barsoom/Volumes/iTunes/Movies
#
LIVE=jwooten37830.com
host=$(hostname)
if [ $host != $LIVE ]
then
    echo "This command is only runnable on $LIVE"
    echo "This hostname is: $host"
    exit
fi
rsync -vaz /Volumes/SeagateTimeCapsule-2/Movies --rsh="ssh -l woo" barsoom:/Volumes/iTunes
echo "All Done!"
