#!/bin/bash
#
# Definition: sync iTunes Movies from barsoom /Volumes/iTunes/Movies to local
#
#
#   This is only run on barsoom, so check for that.
#
LIVE=jwooten37830.com
host=$(hostname)
if [ $host != $LIVE ]
then
    echo "This command is only runnable on $LIVE"
    echo "This hostname is: $host"
    exit
fi
rsync -vaz --rsh="ssh -l woo" barsoom:/Volumes/iTunes/Movies ~
echo "All Done!"
