#!/bin/bash
if [[ $# -eq 0 ]]; then
    echo 'Useage: search some_phrase'
    exit 0
fi
look_for()  {
result=`grep -i $1 $2`
if [ ! -z "$result" ]
    then
      echo "Searching $3"
      echo
      echo "$result"
      echo
    fi
    }

#echo "Searching diary"
#echo
#grep $1 ~/Dropbox/Personal/Documents/Notes/.diary
pattern=$1
NOTES=$CLOUD/Documents/Personal/Documents/Notes
look_for $pattern "$NOTES/.todo" "ToDo"
look_for $pattern "/Users/woo/bin/alias" "~/bin/alias"
look_for $pattern "$NOTES/bin_scripts.csv" "bin scripts documentation file"
look_for $pattern "$NOTES/Language.txt"  "Language"
#| sed 's:~/Dropbox/Personal/Documents/Notes/::'`
look_for $pattern "$NOTES/Port_Starboard.txt" "Port Starboard"
look_for $pattern "$NOTES/Restaurants.txt" "Restaurants"
# This one has to be different to handle searching the directory
result=`ls -l ~/bin | grep -- -.. | grep $1`
if [ ! -z "$result" ]
  then
     echo "Searching ~/bin"
     echo
     echo "$result"
     echo
  fi
echo
# This one searches a directory and then each of special files within
echo "Searching Journal"
echo
echo
for fullpath in $CLOUD/Documents/Personal/Documents/Notes/Journal_*.txt; do
   filename="${fullpath##*/}"                      # Strip longest match of */ from start
   dir="${fullpath:0:${#fullpath} - ${#filename}}" # Substring from 0 thru pos of filename
   base="${filename%.[^.]*}"                       # Strip shortest match of . plus at least one non-dot char from end
   ext="${filename:${#base} + 1}"                  # Substring from len of base thru end
   if [[ -z "$base" && -n "$ext" ]]; then          # If we have an extension and no base, it's really the base
       base=".$ext"
       ext=""
   fi
   if  grep -n -i -q $1 $fullpath; then

      echo "-----------$base--------"
      grep -n -i $1 $fullpath 
      echo
    fi

done
echo
echo "All Done!"
