#!/bin/bash

keytype="rsa"
while getopts "t:" opt; do
   case $opt in
	"t")
		keytype=$OPTARG;;
   esac
done
shift $((OPTIND - 1))

if [[ $# != 1 ]]; then
	echo "Usage: $0 [-t rsa|dsa] [user]@host"
	exit
fi

KEYFILE=~/.ssh/id_$keytype
AUTHFILE=.ssh/authorized_keys

if [[ ! -e $KEYFILE ]]; then
	echo "Creating key..."
	ssh-keygen -t $keytype -f $KEYFILE
fi
if [[ -e $KEYFILE ]]; then
	echo "Logging in..."
	ssh $1 "[[ -d .ssh ]] || mkdir .ssh && [[ -e $AUTHFILE ]] || touch $AUTHFILE && chmod 0600 $AUTHFILE && cat - >> $AUTHFILE" < $KEYFILE.pub
fi
echo "All Done!"

