#!/bin/bash
#
# Get the stats for this machine
#
# Version: 1.0
# Author: John Wooten, Ph.D.
# Date: 20 April 2014
#
uptime
useage=`memory.sh`
echo "Memory Useage: $useage% "
myDisk=`df | awk '/dev\/disk0s2/ && NF>1 {print $5}' | sed 's/\%//'`

echo "Disk Usage: $myDisk%"
